In [1]:
""" Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?"""

' Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?'

In [3]:
import numpy as np
import pandas as pd
import math

In [4]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
mat_array = np.array(mat) #riformattazione array con numpy
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
mat_array.shape #ispeziona la dimensione del nostro array

(3, 5)

In [8]:
mat_array[0,:]


array([0, 1, 2, 3, 4])

In [9]:
mat_array[1,2]  #per accedere singolarmente al singolo elemento

7

In [10]:
"""Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() 
e la variabile .pi la riconoscete? """

'Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() \ne la variabile .pi la riconoscete? '

In [22]:
x = math.sin(90) #restituisce il sin di 15
print("Sin di 90 è", x, "in radianti")

Sin di 90 è 0.8939966636005579 in radianti


In [16]:
y = math.cos(90)
print("Sin di 90 è", x, "in radianti")

-0.4480736161291701

In [23]:
z = math.factorial(4)
z

24

In [ ]:
"""L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
trasformiamola in un array NumPy (casting): lst = np.array(lst) e
rispondiamo alle domande del CEO della Object SpA: 
• qual è stata la vendita massima mensile? E quella minima? 
• quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
• quali sono le vendite minori di 3000 oggetti? 5 
• in media quanti oggetti sono stati venduti al mese?"""

In [24]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
lst = np.array(lst)

In [25]:
print(lst.max()) # vendita max mensile

8150


In [26]:
print(lst.min()) # vendita minima mensile

1280


In [28]:
print(lst.mean()) # vendita media mensile

4634.166666666667


In [31]:
filter = lst[lst>4999] # genera condizione estraendo i valori che soddisfando la [] restiutuento T o F
print(filter)

[5500 7200 6410 8150 7100 5350]


In [35]:
print("quanti sono :", len(filter))

quanti sono : 6


In [34]:
filter_min = lst[lst<3000]
print(filter_min)

[2000 1280 1900 2500]


In [39]:
print("media al mese arrotondata a 2 cifre è", round(lst.mean(), 2)) # vendita media mensile arrotondata di 2 decimali

media al mese arrotondata a 2 cifre è 4634.17


In [ ]:
""" Consideriamo il seguente dizionario:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000} 
Consideriamo ora la seguente Series:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
index=range(1997, 2005)) 
Possiamo accedere alle stesse informazioni nello stesso modo:
fatturati_dict[1997] fatturati_series[1997] 
Dunque qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?

In [40]:
#Dizionario
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [47]:
#Serie Pandas
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index = range(1997, 2005))

In [42]:
#Accesso tramite chiave x, restituisce {x:y}
fatturati_dict[1997] 

12000

In [43]:
print("Tipo di valore del dizionario", type(fatturati_dict[1997]))

Tipo di valore del dizionario <class 'int'>


In [45]:
fatturati_series[1997] 

12000

In [44]:
print("Tipo di valore della serie pandas", type(fatturati_series[1997]))

Tipo di valore della serie pandas <class 'numpy.int64'>


In [48]:
print("Massimo della serie\n", fatturati_series.max())

Massimo della serie
 25000


In [51]:
print("Between\n", fatturati_series[fatturati_series.between(15_000, 20_000)])

Between
 1998    15000
1999    20000
2002    17000
dtype: int64


In [ ]:
""" L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray:
import numpy as np stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: • con un ciclo for
con masking"""

In [52]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] ) 
print(stipendi)

[ 100  200  300  400  500  600  700  800  900 1000]


In [58]:
# Raddoppiare gli stipendi tramite il ciclo FOR

lista_stipendi_raddoppiati = []
print(stipendi[1])

200


In [59]:
for stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio * 2 )
print("Lista stipendi raddoppiati", lista_stipendi_raddoppiati)

Lista stipendi raddoppiati [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
